### ISSUE TITLE
Typo in the in-game text.

### ISSUE THREAD

**Issue by RaptorZX4** [DerekPascarella/NakoruruTheGiftSheGaveMe-EnglishPatchDreamcast#1]
"enoying" where it should be "enjoying". It's during the first time you play a musical instrument (which really look like an ocarina)

![20230614_194242](https://github.com/DerekPascarella/NakoruruTheGiftSheGaveMe-EnglishPatchDreamcast/assets/110866048/3f0239ae-4e7e-4ed4-9851-685fba648c39)

**Comment by DerekPascarella** [comment]
Thank you for the report. This typo will be fixed in a future release.

**Comment by DerekPascarella** [comment]
Version 1.1 update released, issue fixed.
